
services:
  android:
    build:
      context: .
      dockerfile: Dockerfile.android
    container_name: android
    privileged: true
    environment:
      - EMULATOR_DEVICE=Samsung Galaxy S10
      - WEB_VNC=true
      - WEB_LOG=true
      - WEB_LOG_PORT=9000
      - ENV_LOG_PATH=/var/log/
      - APPIUM=true
    volumes:
      - data:/home/androidusr
      - root:/root
    ports:
      - "6080:6080"
      - "4723:4723"
      - "9005:9000"
      - "5554:5554"
      - "5555:5555"
    devices:
      - "/dev/kvm:/dev/kvm"
    restart: always
    networks:
      - my-network


  apk-installer:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: apk-installer
    depends_on:
      - android
    environment:
      - ANDROID_CONTAINER_NAME=android
      - APK_PATH=/apk/test_app/looky.apk
    entrypoint: ["/bin/bash", "-c", "/install-apk.sh"]
    restart: "no"
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "adb", "-s", "android:5555", "shell", "getprop", "sys.boot_completed"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 300s
    volumes:
      - shared_volume:/shared

  monitor:
    build: .
    container_name: monitor
    depends_on:
      apk-installer:
        condition: service_healthy
    env_file:
      - .env  # Добавляем ссылку на файл .env
    networks:
      - my-network
    volumes:
      - shared_volume:/shared

networks:
  my-network:
    driver: bridge

volumes:
  data:
  root:
  shared_volume:
