
services:
  android:
    build:
      context: .
      dockerfile: Dockerfile.android
    container_name: android
    privileged: true
    environment:
      - EMULATOR_DEVICE=Samsung Galaxy S10
      - WEB_VNC=true
      - WEB_LOG=true
      - WEB_LOG_PORT=9000
      - ENV_LOG_PATH=/var/log/
      - APPIUM=true
    volumes:
      - data:/home/androidusr
      - root:/root
    ports:
      - "6080:6080"
      - "4723:4723"
      - "9005:9000"
    devices:
      - "/dev/kvm:/dev/kvm"
    restart: always
    networks:
      - my-network


  apk-installer:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: apk-installer
    depends_on:
      - android
    environment:
      - ANDROID_CONTAINER_NAME=android
      - APK_PATH=/apk/test_app/looky.apk
    entrypoint: ["/bin/bash", "-c", "/install-apk.sh"]
    restart: "no"
    networks:
      - my-network
    healthcheck:
      test: ["CMD-SHELL", "adb -s emulator-5554 shell getprop sys.boot_completed | grep 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 300s
    volumes:
      - shared_volume:/shared

  monitor:
    build: .
    container_name: monitor
    #depends_on:
     # apk-installer:
      #  condition: service_healthy   
    #command: /bin/bash -c "while ! docker logs apk-installer 2>&1 | grep -q 'APK installation complete'; do sleep 5; done; echo 'APK installation complete. Starting monitor container.'"
    ports:
      - "5555:5555" # Добавил порт 
    env_file:
      - .env  
    networks:
      - my-network
    volumes:
      - shared_volume:/shared

networks:
  my-network:
    driver: bridge

volumes:
  data:
  root:
  shared_volume:
